version: '3.8'

services:
  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: datab4
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: .
    # image: flaskapi:0.2
    depends_on:
      - db
    environment:
      STAGE: development
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:pass@db/datab4
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      # - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  